name: Build Maven Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Faz checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configura o Java (versão 21 ou superior)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # 3️⃣ Executa o Maven para compilar e empacotar o projeto
      - name: Build with Maven
        run: mvn -B clean package

      # 4️⃣ (Opcional) Copia o .jar para a raiz do repositório
      - name: Copy JAR to root
        run: cp target/*.jar .

      # 5️⃣ Publica o artefacto gerado
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ToDoApp-jar
          path: target/*.jar
