name: Build and Deploy ToDoApp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Faz checkout do código do repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Configura o JDK (Java 21 ou superior)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # 3️⃣ Executa o build com Maven para gerar o .jar
      - name: Build with Maven
        run: mvn -B clean package

      # 4️⃣ (Opcional) Copia o .jar para a raiz do repositório
      - name: Copy JAR to root
        run: cp target/*.jar .

      # 5️⃣ Publica o .jar gerado como artefacto do workflow
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ToDoApp-jar
          path: target/*.jar