name: CI Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn -B -DskipTests clean package

      - name: (Opcional) Copiar JAR para a raiz do workspace
        run: cp target/*.jar . || true

      - name: Upload artifact (JAR)
        uses: actions/upload-artifact@v4
        with:
          name: todoapp-jar
          path: |
            target/*.jar
            *.jar