#yml
name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonar:
    name: Run SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Cache SonarQube Scanner
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/sonar-project.properties') }}
          restore-keys: |
            ${{ runner.os }}-sonar-

      - name: Install dependencies
        run: |
          ./mvnw clean install

      - name: Run SonarQube Scanner
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          token: ${{ secrets.SONAR_TOKEN }}

      - name: Wait for SonarQube analysis to complete
        run: |
          curl -s --fail -X POST "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ github.repository }}" \
          -H "Authorization: Bearer ${{ secrets.SONAR_TOKEN }}" \
          --retry 3 --retry-delay 5
